allowBuilds:
  '@parcel/watcher': false
  esbuild: true
  sharp: true

minimumReleaseAge: 10080

overrides:
  'picomatch@>=4.0.0 <4.0.4': 4.0.4
  'yaml@>=2.0.0 <2.8.3': 2.8.3
  tar: '>=7.5.11'
  undici: '>=7.24.0'
