---

name: main

on: [push]

env:
  NODE_VERSION: '18.x'

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: pnpm
        run: npm install -g pnpm --registry=https://registry.npmjs.org

      - name: Get pnpm cache directory
        uses: actions/cache@v3
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install app dependencies
        run: pnpm install

      - name: Lint app files
        run: pnpm run lint

      - name: Build app
        run: pnpm run build
